### ISSUE TITLE
couldn't inline method call 'kauLaunchAbout' into .....

### ISSUE THREAD

**Issue by YvesCheung** [AllanWang/KAU#125]
![image](https://user-images.githubusercontent.com/18024705/34565842-55b20c2e-f197-11e7-94a6-edd521f3fc0f.png)

**Comment by YvesCheung** [comment]
![image](https://user-images.githubusercontent.com/18024705/34566055-2abc01e0-f198-11e7-9c23-1120fe598213.png)

**Comment by YvesCheung** [comment]
I move the method 'Activity.kauLaunchAbout()' into MainActivity.kt and it works
thousands of Grass Mud Horses run through my heart

**Comment by AllanWang** [comment]
I'm aware of the issue. It came from the recent change of reified generics as opposed to passing the class as you would in Java.

I've reported it to the Kotlin team [here](https://youtrack.jetbrains.com/issue/KT-22086)
