### ISSUE TITLE
SearchView is not shown in multiwindow mode

### ISSUE THREAD

**Issue by jahirfiquitiva** [AllanWang/KAU#130]
When the app is in multiwindow mode and shown in the bottom part of the screen, the search view is not shown.

The second screenshot is how it's shown when the app occupies ~3/4 of the screen.

**Thanks**

![screenshot_20180121-131848](https://user-images.githubusercontent.com/10360816/35197503-02b32dea-feae-11e7-85f7-179bc1e3cde3.png)

![screenshot_20180121-132255](https://user-images.githubusercontent.com/10360816/35197536-613ad21e-feae-11e7-8424-d8f553767c2e.png)

**Comment by AllanWang** [comment]
Thanks. I'll see if I can replicate it.

**Comment by AllanWang** [comment]
Turns out I actually fixed this in https://github.com/AllanWang/KAU/commit/2a9d5916a2acd0b468b9aa28977021fdd483e2aa

I just didn't update the sample app yet. This fix has been present as of 3.6.2

**Comment by jahirfiquitiva** [comment]
@AllanWang 

Awesome! Thank you so much :D
