### ISSUE TITLE
Disable seekbar when the contract enabler is false

### ISSUE THREAD

**Issue by Thames1990** [AllanWang/KAU#133]
I'm trying to disable the seekbar of a preference in a `KPrefActivity` when the `KPrefSeekbar.KPrefSeekbarContract` enabler is `false`.

This is my contract:
```
fun KPrefSeekbar.KPrefSeekbarContract.dependsOnLocationPermission() {
    enabler = { hasPermission(Manifest.permission.ACCESS_FINE_LOCATION) }
    onDisabledClick = { snackbar(R.string.requires_location_permission) }
}
```

As you can see in this [video](https://youtu.be/oVtkGjCTeGg), the preference is disabled, but the seekbar is still enabled. Can you guide me how to disable it?

**Comment by AllanWang** [comment]
Thanks for the report. I would consider this as a bug, as I only disabled clicks when the preference wasn't disabled. I will be fixing this shortly

**Comment by AllanWang** [comment]
You may use 91e4b0c immediately, or wait for the next release.
