### ISSUE TITLE
Seekbar increments not affecting result

### ISSUE THREAD

**Issue by Thames1990** [AllanWang/KAU#145]
I'm trying to limit seekbar increments by steps. The user should be able to set a value between 0 and 10000, but only in steps of 100.

```
seekbar(
    ...
    builder = {
        min = 0
        max = 10000
        increments = 100
    }
)
```

With this implementation each value between `min` and `max` is a valid argument.

Either i'm not understanding the `increments` field, or the implementation is not working.

**Comment by AllanWang** [comment]
Sorry for the late reply. I remember seeing this and I thought I resolved it already. I have replicated the issue and I will look into it shortly

**Comment by AllanWang** [comment]
You may set the build number to 8b4048d to test this.
