### ISSUE TITLE
SearchView not on top of toolbar in one activity. Fine in the other

### ISSUE THREAD

**Issue by bignadad** [AllanWang/KAU#153]
I have 2 activities using the same theme but the searchview is offset on the child activity. 
In my main activity it works fine. But in my child activity that is launched from my main its offset.

I do have a tab layout in the parent activity.

Any ideas what to look for to fix this?

![screenshot_20180819-232521_memoria](https://user-images.githubusercontent.com/1048928/44319138-fcee4480-a407-11e8-8616-15afcebcd026.jpg)
![screenshot_20180819-232458_memoria](https://user-images.githubusercontent.com/1048928/44319139-fcee4480-a407-11e8-8d0e-2249f3184ed8.jpg)

**Comment by AllanWang** [comment]
Can you elaborate on what you mean by "child activity"? How are the styles different between the two activities? My guess is that in one of them you've set it to fit the system window, as the offset looks to be the same as the status bar height. There's a way to [override the offset](https://github.com/AllanWang/KAU/blob/a0377be622f21b4c6a7d8828505c1e95efab1254/searchview/src/main/kotlin/ca/allanwang/kau/searchview/SearchView.kt#L261) when it draws if you'd like to look into that.

I won't be able to look into it myself until after my internship.

**Comment by bignadad** [comment]
child activity meaning the activity that is working is starting it. the styles are the same and not using any systemfitwindows. 

I tried this 'searchView?.menuY = -resources.getStatusBarHeight()' right after the bind searchview but didnt do anything. Am I calling it correctly?

**Comment by bignadad** [comment]
sorry i realize now you say in comments to call in the open listener. I will see if that works

**Comment by bignadad** [comment]
That fixed it. Thank you.

**Comment by AllanWang** [comment]
Great! I recommend you make it relative, as in using "-=" rather than "=". This probably works now because menuY is 0, but in the event your toolbar is not at the top, you'll have a problem again.
