### ISSUE TITLE
Searchview Hint Text Color

### ISSUE THREAD

**Issue by bignadad** [AllanWang/KAU#154]
Is there a way to set the color for the hintText? I know I can set the text, but cannot figure out how to change the color

**Comment by AllanWang** [comment]
It was supposed to be all included. I'll add the hint text color after my internship.

**Comment by AllanWang** [comment]
For now you can set it by getting the edit text through findViewById(R.id. kau_search_edit_text).

I'm planning for some major refactoring for the next release as I'm converting to androidx and moving some things to newer material design standards so it may take a while.

**Comment by bignadad** [comment]
That worked. thought i had tried that but it works now. thanks

**Comment by AllanWang** [comment]
I did a quick fix at commit dca58435ac0ca941a488c117363e2920e083dfa9.

You can replace the version with that and see if it works.

**Comment by AllanWang** [comment]
Oops. Didn't pass lint. I will close this again with the latest commit when I fix it

**Comment by AllanWang** [comment]
Fixed in 6af0c6f. ConstraintLayout dependency has been updated
