### ISSUE TITLE
Is it safe to call object KPref.initialize() multiple times from different activities' onCreate?

### ISSUE THREAD

**Issue by jimbo1qaz** [AllanWang/KAU#165]
I'm learning Android development. Currently I have a main activity with `object cfg: KPref()` and a "file open" activity. I'm planning to add intent filters to launch "file open" directly, so my main activity's `onCreate` won't be called. Can I call `KPref.initialize()` from both my main activity and file open's `onCreate`, or should I only call initialize when opening from an external intent?

`fun initialize(c: Context, preferenceName: String) {`

`sp = c.applicationContext.getSharedPreferences(preferenceName, Context.MODE_PRIVATE)`

I don't know if it's safe from the perspective of `prefMap`-`sp` synchronization, lost writes, etc.

**Comment by AllanWang** [comment]
`SharedPreferences`, along with all the getters in kpref should be thread safe. However, you shouldn't be initializing it multiple times.

The benefit of initializing in the application is that it will always be loaded before any activity, even if you switch activities.
