### ISSUE TITLE
Q: Will ElasticDragDismissFrameLayout work if using MotionLayout?

### ISSUE THREAD

**Issue by paolovalerdi** [AllanWang/KAU#216]
I've got little time to test this out hope you can address this question :) thanks.

**Comment by AllanWang** [comment]
I personally don't use MotionLayout, but I don't see why it would be an issue unless you plan on animating while the user is swiping. Keep in mind that the layout is based on [plaid](https://github.com/android/plaid) so you may want to look there for some more interesting components.

It doesn't play well with some elements like CoordinatorLayout when I checked it with another project.
